
version: '3.9'

services:
  web:
    build: .
    volumes:
      - app-data:/app/data
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  # PostgreSQL database service
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  app-data:
  db-data:
    # Named volume for persisting PostgreSQL data

